[build-system]
requires = ["setuptools>=61.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "shakalizer"
version = "0.1.1"
description = "A lightweight library for deep-frying images and reducing quality"
readme = "README.md"
authors = [
    { name = "wh0amitg" }
]
license = { text = "MIT" }
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
requires-python = ">=3.7"
dependencies = [
    "Pillow>=9.0.0"
]
